[dp]
b_range = [1, 2, 3, 4, 5, 6, 7, 8, 9]
j_range = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27]
outs_range = [-1, 0, 1, 2, 3]
bases_range = [0,1]
NUM_BATTERS = 9
NUM_INNINGS = 9
MAX_R = 40
DEFAULT_SIMS = 1000
DEFAULT_STR = "redsox_2023.csv"
PROB_EXPORT_STR = "probmemo.csv"
F_EXPORT_STR = "fmemo.csv"
G_EXPORT_STR = "gmemo.csv"
H_EXPORT_STR = "hmemo.csv"
PLOTHIST_EXPORT_STR = "histogram-comparison.png"
PLOTDIFF_EXPORT_STR = "dpsim-difference.png"
PERMUTATION_EXPORT_STR = "lineup-results.csv"
TOP_N = 15
